### ISSUE TITLE
doubt about the command about ">", "<","+","-"

### ISSUE THREAD

**Issue by mudongliang** [HexHive/printbf#2]
- > == dataptr++ (%1$65535d%1$.*1$d%2$hn)
- < == dataptr-- (%1$.*1$d %2$hn)
- \+ == dataptr++ (%3$.3$d %4$hhn)
- \- == datapr-- (%3$255d%3$.3$d%4$hhn -- plus check for ovfl)

Why do ">" and "+" map to the same command? The same to "<" and "-"!

P.S. the word "datapr" is error, you may mean "dataptr"!

**Comment by gannimo** [comment]
Thanks for mentioning the typo. In the sources, there's a \* in front of +/- of dataptr.
