### ISSUE TITLE
Oops inception on the README

### ISSUE THREAD

**Issue by rdebath** [HexHive/printbf#7]
A true double BF interpreter.

Minor issue on your README, the C translations `*dataptr++` and `*dataptr--` change the pointer not the cell contents, you want `(*dataptr)++` or `++*dataptr`.

Edit: Oh dear, and your slides.

**Comment by gannimo** [comment]
Thanks a lot; operator precedence is hard, especially in pseudo code that you don't run. I've updated the README and the slides. Thanks for pointing it out! :)
